export const AZERBAIJAN_REGION_GROUPS = [
  {
    id: 'baku_districts',
    name: 'Bakı rayonları',
    mapCity: 'Baku',
    regions: [
      { id: 'baku-bineqedi', name: 'Binəqədi rayonu' },
      { id: 'baku-garadag', name: 'Qaradağ rayonu' },
      { id: 'baku-khatai', name: 'Xətai rayonu' },
      { id: 'baku-khazar', name: 'Xəzər rayonu' },
      { id: 'baku-narimanov', name: 'Nərimanov rayonu' },
      { id: 'baku-nasimi', name: 'Nəsimi rayonu' },
      { id: 'baku-nizami', name: 'Nizami rayonu' },
      { id: 'baku-pirallahi', name: 'Pirallahı rayonu' },
      { id: 'baku-sabunchu', name: 'Sabunçu rayonu' },
      { id: 'baku-sabail', name: 'Səbail rayonu' },
      { id: 'baku-surakhani', name: 'Suraxanı rayonu' },
      { id: 'baku-yasamal', name: 'Yasamal rayonu' },
    ],
  },
  {
    id: 'ganja_districts',
    name: 'Gəncə rayonları',
    mapCity: 'Ganja',
    regions: [
      { id: 'ganja-nizami', name: 'Nizami rayonu' },
      { id: 'ganja-kepez', name: 'Kəpəz rayonu' },
    ],
  },
  {
    id: 'azerbaijan_regions',
    name: 'Azərbaycan rayonları',
    regions: [
      { id: 'absheron', name: 'Abşeron rayonu' },
      { id: 'agcabadi', name: 'Ağcabədi rayonu' },
      { id: 'agdam', name: 'Ağdam rayonu' },
      { id: 'agdash', name: 'Ağdaş rayonu' },
      { id: 'agdara', name: 'Ağdərə rayonu' },
      { id: 'agstafa', name: 'Ağstafa rayonu' },
      { id: 'agsu', name: 'Ağsu rayonu' },
      { id: 'astara', name: 'Astara rayonu' },
      { id: 'balakan', name: 'Balakən rayonu' },
      { id: 'beylagan', name: 'Beyləqan rayonu' },
      { id: 'berde', name: 'Bərdə rayonu' },
      { id: 'bilasuvar', name: 'Biləsuvar rayonu' },
      { id: 'cabrayil', name: 'Cəbrayıl rayonu' },
      { id: 'celilabad', name: 'Cəlilabad rayonu' },
      { id: 'dashkesen', name: 'Daşkəsən rayonu' },
      { id: 'fuzuli', name: 'Füzuli rayonu' },
      { id: 'gedebey', name: 'Gədəbəy rayonu' },
      { id: 'goranboy', name: 'Goranboy rayonu' },
      { id: 'goychay', name: 'Göyçay rayonu' },
      { id: 'goygol', name: 'Göygöl rayonu' },
      { id: 'hajigabul', name: 'Hacıqabul rayonu' },
      { id: 'khachmaz', name: 'Xaçmaz rayonu' },
      { id: 'khizi', name: 'Xızı rayonu' },
      { id: 'khojali', name: 'Xocalı rayonu' },
      { id: 'khojavend', name: 'Xocavənd rayonu' },
      { id: 'imishli', name: 'İmişli rayonu' },
      { id: 'ismayilli', name: 'İsmayıllı rayonu' },
      { id: 'kalbajar', name: 'Kəlbəcər rayonu' },
      { id: 'kurdamir', name: 'Kürdəmir rayonu' },
      { id: 'qakh', name: 'Qax rayonu' },
      { id: 'qazakh', name: 'Qazax rayonu' },
      { id: 'gabala', name: 'Qəbələ rayonu' },
      { id: 'gobustan', name: 'Qobustan rayonu' },
      { id: 'quba', name: 'Quba rayonu' },
      { id: 'qubadli', name: 'Qubadlı rayonu' },
      { id: 'qusar', name: 'Qusar rayonu' },
      { id: 'lachin', name: 'Laçın rayonu' },
      { id: 'lerik', name: 'Lerik rayonu' },
      { id: 'lankaran', name: 'Lənkəran rayonu' },
      { id: 'masalli', name: 'Masallı rayonu' },
      { id: 'neftchala', name: 'Neftçala rayonu' },
      { id: 'oguz', name: 'Oğuz rayonu' },
      { id: 'saatli', name: 'Saatlı rayonu' },
      { id: 'sabirabad', name: 'Sabirabad rayonu' },
      { id: 'salyan', name: 'Salyan rayonu' },
      { id: 'samukh', name: 'Samux rayonu' },
      { id: 'siyezen', name: 'Siyəzən rayonu' },
      { id: 'shabran', name: 'Şabran rayonu' },
      { id: 'shamakhi', name: 'Şamaxı rayonu' },
      { id: 'shaki', name: 'Şəki rayonu' },
      { id: 'shamkir', name: 'Şəmkir rayonu' },
      { id: 'shusha', name: 'Şuşa rayonu' },
      { id: 'terter', name: 'Tərtər rayonu' },
      { id: 'tovuz', name: 'Tovuz rayonu' },
      { id: 'ucar', name: 'Ucar rayonu' },
      { id: 'yardimli', name: 'Yardımlı rayonu' },
      { id: 'yevlakh', name: 'Yevlax rayonu' },
      { id: 'zaqatala', name: 'Zaqatala rayonu' },
      { id: 'zangilan', name: 'Zəngilan rayonu' },
      { id: 'zardab', name: 'Zərdab rayonu' },
    ],
  },
  {
    id: 'nakhchivan_mr',
    name: 'Naxçıvan Muxtar Respublikası',
    mapCity: 'Nakhchivan',
    regions: [
      { id: 'nakhchivan-babek', name: 'Babək rayonu' },
      { id: 'nakhchivan-julfa', name: 'Culfa rayonu' },
      { id: 'nakhchivan-kangarli', name: 'Kəngərli rayonu' },
      { id: 'nakhchivan-ordubad', name: 'Ordubad rayonu' },
      { id: 'nakhchivan-sadarak', name: 'Sədərək rayonu' },
      { id: 'nakhchivan-shahbuz', name: 'Şahbuz rayonu' },
      { id: 'nakhchivan-sharur', name: 'Şərur rayonu' },
    ],
  },
];